services:
  - type: web
    name: telegram-upload-bot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: UPLOAD_CHANNEL_ID
        sync: false
      - key: DB_CHANNEL_ID
        sync: false
      - key: DB_PATH
        value: /data/database.sqlite3
      - key: JOB_DB_PATH
        value: /data/jobs.sqlite
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
    healthCheckPath: /health
    dockerfilePath: ./Dockerfile
    autoRestart: true